# Generated by Django 4.0.1 on 2022-02-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_passwords', '0002_category_user_alter_account_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
