# Generated by Django 4.0.1 on 2022-02-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_passwords', '0003_alter_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.BinaryField(editable=True, max_length=255),
        ),
    ]
